#!/usr/bin/env bash
# MiroFish one-command server setup (Ubuntu 22.04/24.04, run as root).
#
#   curl -fsSL https://raw.githubusercontent.com/ker4anin-arch/mirofish/claude/focused-knuth-3zzg2c/deploy/vps-setup.sh | bash
#
# Re-running is safe: it updates the code and images and keeps your .env.
# Optional environment overrides (otherwise you are asked):
#   LLM_API_KEY, BASIC_AUTH_USER, BASIC_AUTH_PASSWORD, SITE_ADDRESS (domain or ":80")
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/ker4anin-arch/mirofish.git}"
BRANCH="${BRANCH:-claude/focused-knuth-3zzg2c}"
APP_DIR="${APP_DIR:-/opt/mirofish}"
COMPOSE=(docker compose -f docker-compose.vps.yml)

log() { printf '\n\033[1;32m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }
ask() {  # ask VAR "prompt" [secret]
  local __var=$1 __prompt=$2 __secret=${3:-} __value=""
  if [ -n "${!__var:-}" ]; then return; fi
  if [ -n "$__secret" ]; then read -r -s -p "$__prompt" __value </dev/tty; echo; else read -r -p "$__prompt" __value </dev/tty; fi
  printf -v "$__var" '%s' "$__value"
}

[ "$(id -u)" -eq 0 ] || die "run as root (sudo -i)"

log "Installing base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq git curl ca-certificates openssl >/dev/null

if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker"
  if ! curl -fsSL https://get.docker.com | sh; then
    echo "get.docker.com unavailable, falling back to Ubuntu packages"
    apt-get install -y -qq docker.io docker-compose-v2 >/dev/null
  fi
fi
docker compose version >/dev/null 2>&1 || apt-get install -y -qq docker-compose-v2 >/dev/null \
  || apt-get install -y -qq docker-compose-plugin >/dev/null
systemctl enable --now docker >/dev/null 2>&1 || true

if [ "$(swapon --show | wc -l)" -eq 0 ]; then
  log "Adding 2 GB swap (protects simulations from running out of memory)"
  if fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile; then
    grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  else
    rm -f /swapfile; echo "Could not enable swap (not supported here); continuing without it"
  fi
fi

if command -v ufw >/dev/null 2>&1; then
  log "Firewall: allowing SSH, HTTP, HTTPS"
  ufw allow OpenSSH >/dev/null; ufw allow 80/tcp >/dev/null; ufw allow 443/tcp >/dev/null
  ufw --force enable >/dev/null
fi

log "Fetching MiroFish ($BRANCH)"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch -q origin "$BRANCH"
  git -C "$APP_DIR" checkout -q "$BRANCH"
  git -C "$APP_DIR" reset -q --hard "origin/$BRANCH"
else
  git clone -q --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"
mkdir -p backend/uploads

if [ ! -f .env ]; then
  log "First-time configuration"
  ask LLM_API_KEY "DeepSeek API key: " secret
  [ -n "$LLM_API_KEY" ] || die "DeepSeek API key is required"
  BASIC_AUTH_USER="${BASIC_AUTH_USER:-admin}"
  if [ -z "${BASIC_AUTH_PASSWORD:-}" ]; then
    BASIC_AUTH_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-16)"
    GENERATED_PASSWORD=1
  fi
  SITE_ADDRESS="${SITE_ADDRESS:-:80}"
  CADDY_IMAGE="${IMAGE_PREFIX:-ghcr.io/ker4anin-arch}/mirofish-caddy:latest"
  BASIC_AUTH_HASH="$(docker run --rm "$CADDY_IMAGE" caddy hash-password --plaintext "$BASIC_AUTH_PASSWORD")"
  umask 077
  cat > .env <<EOF
# Generated by deploy/vps-setup.sh — keep this file private.
LLM_API_KEY=${LLM_API_KEY}
LLM_BASE_URL=https://api.deepseek.com/v1
LLM_MODEL_NAME=deepseek-flash
NEO4J_PASSWORD=$(openssl rand -hex 16)
BASIC_AUTH_USER=${BASIC_AUTH_USER}
BASIC_AUTH_HASH='${BASIC_AUTH_HASH}'
SITE_ADDRESS=${SITE_ADDRESS}
EOF
else
  log "Keeping existing .env"
fi

if [ -z "${SKIP_PULL:-}" ]; then
  log "Pulling images"
  "${COMPOSE[@]}" pull
fi

log "Starting MiroFish"
"${COMPOSE[@]}" up -d --remove-orphans

log "Waiting for the backend (first start builds database indexes)"
for _ in $(seq 1 100); do
  curl -fs -m 2 http://127.0.0.1:5001/health >/dev/null 2>&1 && break
  sleep 3
done
curl -fs -m 2 http://127.0.0.1:5001/health >/dev/null || die "backend did not start; check: docker logs mirofish"
docker logs mirofish 2>&1 | grep -q "WARNING: knowledge graph store unavailable" \
  && echo "WARNING: backend cannot reach Neo4j; check: docker logs mirofish-neo4j"

ADDRESS="$(grep '^SITE_ADDRESS=' .env | cut -d= -f2)"
if [ "$ADDRESS" = ":80" ]; then
  URL="http://$(curl -fs -m 5 https://api.ipify.org || hostname -I | awk '{print $1}')"
else
  URL="https://$ADDRESS"
fi
log "MiroFish is running: $URL"
echo "   user:     $(grep '^BASIC_AUTH_USER=' .env | cut -d= -f2)"
if [ "${GENERATED_PASSWORD:-}" = 1 ]; then
  echo "   password: $BASIC_AUTH_PASSWORD   (generated — save it now, it is not stored in plain text)"
fi
echo
echo "Update later:  cd $APP_DIR && bash deploy/vps-setup.sh"
echo "Logs:          docker logs -f mirofish"
